name: "Security Alerts - Summary"
on:
  workflow_dispatch:
permissions:
  contents: read
  security-events: read
jobs:
  security_alerts_summary:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub Pages branch
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"
          path: "out"
      - name: "Count open security alerts"
        id: open_sec_alerts
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.PAT_SECURITY_EVENTS_SUMMARY }}
        run: |
          OPEN_ALERTS=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/fpasantiago-tmp/vulnado-mirror/dependabot/alerts?state=open&sort=created&direction=desc" --jq 'length')
          echo "OPEN_ALERTS=$(echo $OPEN_ALERTS)" >> "$GITHUB_OUTPUT"
      - name: "Count open security alerts"
        id: fixed_sec_alerts
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.PAT_SECURITY_EVENTS_SUMMARY }}
        run: |
          FIXED_ALERTS=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/fpasantiago-tmp/vulnado-mirror/dependabot/alerts?state=fixed&sort=updated&direction=desc" --jq 'length')
          echo "FIXED_ALERTS=$(echo $FIXED_ALERTS)" >> "$GITHUB_OUTPUT"
      - name: "Echo open and fixed security alerts"
        shell: bash
        run: |
          echo "OPEN alerts: ${{ steps.open_sec_alerts.outputs.OPEN_ALERTS }}"
          echo "Fixed alerts: ${{ steps.fixed_sec_alerts.outputs.FIXED_ALERTS }}"
      - name: "Generate Dashboard"
        uses: ethomson/issue-dashboard@v1
        with:
          config: |
            title: 'Dashboard'
            output:
              format: html
              filename: 'out/dashboard.html'
            sections:
            - title: 'GH Security Alerts'
              widgets:
              - type: 'graph'
                title: 'Alerts by status'
                elements:
                  - title: Open
                    value: 18
                    color: green
                  - title: Fixed
                    value: 16
                    color: red
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Documentation
        run: |
          git add .
          git config user.name 'Dashboard User'
          git config user.email 'nobody@nowhere'
          git commit -m 'Documentation update' --allow-empty
          git push origin gh-pages
        working-directory: out
