name: "Security Alerts - Summary"
on:
  workflow_dispatch:
permissions:
  contents: read
  security-events: read
jobs:
  security_alerts_summary:
    runs-on: ubuntu-latest
    steps:
      - name: "Count open security alerts"
        id: open_sec_alerts
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.PAT_SECURITY_EVENTS_SUMMARY }}
        run: |
          OPEN_ALERTS=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/fpasantiago-tmp/vulnado-mirror/dependabot/alerts?state=open&sort=created&direction=desc" --jq 'length')
          echo "OPEN_ALERTS=$(echo $OPEN_ALERTS)" >> "$GITHUB_OUTPUT"
      - name: "Count open security alerts"
        id: fixed_sec_alerts
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.PAT_SECURITY_EVENTS_SUMMARY }}
        run: |
          FIXED_ALERTS=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/fpasantiago-tmp/vulnado-mirror/dependabot/alerts?state=fixed&sort=updated&direction=desc" --jq 'length')
          echo "FIXED_ALERTS=$(echo $FIXED_ALERTS)" >> "$GITHUB_OUTPUT"
      - name: "Echo open and fixed security alerts"
        shell: bash
        run: |
          echo "OPEN alerts: ${{ steps.open_sec_alerts.outputs.OPEN_ALERTS }}"
          echo "Fixed alerts: ${{ steps.fixed_sec_alerts.outputs.FIXED_ALERTS }}"
