name: "Security Alerts - Summary"
on:
  workflow_dispatch:
permissions:
  contents: read
  security-events: read
jobs:
  security_alerts_summary:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.PAT_SECURITY_EVENTS_SUMMARY }}
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -Fstate='open' -Fdirection='desc' \
          "/repos/fpasantiago-tmp/vulnado-mirror/dependabot/alerts?state=open&sort=created&direction=desc"
