name: "Dependency Review - Check PR vulnerable dependencies"
on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: Dependency Review
        id: dependency_review_step
        uses: actions/dependency-review-action@v3
        continue-on-error: true
        with:
          fail-on-severity: moderate
          fail-on-scopes: runtime
          license-check: false
      - name: Print dependency review output
        if: always()
        id: print_dependency_review_output
        shell: bash
        run: |
          echo "Outcome: ${{ toJson(steps.dependency_review_step.outcome) }}"
          echo "Conclusion: ${{ toJson(steps.dependency_review_step.conclusion) }}"
