name: "Dependency Review - Check PR vulnerable dependencies"
on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, edited, ready_for_review, review_requested, synchronize]
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: moderate
          fail-on-scopes: runtime
          license-check: false
